name: opencc
description: A dart library for conversion between Traditional and Simplified Chinese with natvie-assets.
version: 1.2.0-dev.1
repository: https://github.com/lindeer/opencc-dart

environment:
  sdk: 3.10.0-14.0.dev

executables:
  opencc:

dependencies:
  code_assets: ^0.19.0
  hooks: ^0.19.0
  ffi: ^2.1.3
  glob: ^2.1.2
  path: ^1.9.0
  zip2: ^1.0.1

dev_dependencies:
  ffigen: ^19.0.0
  lints: ^6.0.0
  test: ^1.25.15
