name: opencc
description: A dart library for conversion between Traditional and Simplified Chinese with natvie-assets.
version: 1.1.0
repository: https://github.com/lindeer/opencc-dart

environment:
  sdk: ^3.3.0

executables:
  opencc:

dependencies:
  code_assets: any
  hooks: any
  ffi: ^2.1.3
  glob: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  ffigen: ^19.0.0
  lints: ^6.0.0
  test: ^1.25.15
