name: opencc_assets

permissions:
  contents: write

on:
  push:
    branches: [ t/assets ]
    paths:
      - .github/workflows/asset_build.yaml
      - opencc-version
      - tools/compile.sh
    tags:
      - 'prebuild-assets-*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [linux]
        arch: [arm64]

    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4

    - uses: dart-lang/setup-dart@v1
      with:
        sdk: stable

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch == 'arm64' && 'amd64_arm64' || 'amd64_x86' }}
      if: ${{ matrix.os == 'windows' }}

    - run: git clone https://gitlab.com/lindeer/opencc.git lib-src --depth 1 -b $(cat opencc-version)
    - run: |
        mkdir lib-src/build
        mkdir assets

    - name: Build in Docker container
      if: ${{ matrix.os == 'linux'}}
      run: |
        docker pull arm64v8/ubuntu:18.04
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          arm64v8/ubuntu:18.04 /bin/bash tools/compile.sh

    - name: Build ${{ matrix.os }} host
      working-directory: lib-src/build
      if: ${{ matrix.os != 'linux'}}
      run: |
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
        cmake --build . --config Release --target Dictionaries

    - name: Pack assets archive
      working-directory: assets
      if: ${{ matrix.os != 'windows' }}
      env:
        EXT: ${{ matrix.os == 'macos' && 'dylib' || 'so' }}
      run: |
        ls -l ../lib-src/build/src
        cp ../lib-src/build/src/*.${EXT}* .
        mkdir opencc
        cp ../lib-src/build/data/*.ocd2 opencc
        cp ../lib-src/data/config/*.json opencc
        zip -r assets.zip *.${EXT}* opencc

    - name: Pack windows archive
      working-directory: assets
      if: ${{ matrix.os == 'windows' }}
      run: |
        ls -l ../lib-src/build/src
        cp ../lib-src/build/src/Release/*.dll .
        mkdir opencc
        cp ../lib-src/build/data/*.ocd2 opencc
        cp ../lib-src/data/config/*.json opencc
        tar.exe -cf assets.zip *.dll opencc

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencc-${{ matrix.os }}-${{ matrix.arch }}
        path: |
          assets/*.zip
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: assets

      - name: Display structure of downloaded assets
        run: ls -R assets

      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/prebuild-assets')
        with:
          files: 'assets/**'
          fail_on_unmatched_files: true
