name: CI - Build and Test (Multi-arch)

on:
  push:
    branches:
      - t/ci
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [linux, macos, windows]
        arch: [x64, arm64]
        include:
          - os: linux
            arch: x64
            runner: ubuntu-latest
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm

          - os: windows
            runner: windows-latest

          - os: macos
            arch: x64
            runner: macos-latest
        exclude:
          - os: macos
            arch: arm64

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.10.0-14.0.dev

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch == 'arm64' && 'amd64_arm64' || 'amd64_x86' }}
        if: ${{ matrix.os == 'windows' }}

      - run: dart pub get

      - name: Run test cases
        env:
          OPENCC_SHARED_DIR: .dart_tool/share
        run: dart --enable-experiment=native-assets test
